wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.8.19
    cli_version: 0.17.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717177678
    t:
      1:
      - 1
      - 9
      - 41
      - 51
      - 55
      - 79
      2:
      - 1
      - 9
      - 41
      - 51
      - 55
      - 79
      3:
      - 1
      - 23
      4: 3.8.19
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
root_dir:
  desc: null
  value: ./datasets/synthetic/livingroom
dataset_name:
  desc: null
  value: blender
img_wh:
  desc: null
  value:
  - 400
  - 300
spheric_poses:
  desc: null
  value: false
N_emb_xyz:
  desc: null
  value: 10
N_emb_dir:
  desc: null
  value: 4
N_samples:
  desc: null
  value: 64
N_importance:
  desc: null
  value: 64
use_disp:
  desc: null
  value: false
perturb:
  desc: null
  value: 1.0
noise_std:
  desc: null
  value: 1.0
batch_size:
  desc: null
  value: 1024
chunk:
  desc: null
  value: 8192
num_epochs:
  desc: null
  value: 30
num_gpus:
  desc: null
  value: 1
ckpt_path:
  desc: null
  value: null
prefixes_to_ignore:
  desc: null
  value:
  - loss
weight_path:
  desc: null
  value: null
optimizer:
  desc: null
  value: adam
lr:
  desc: null
  value: 0.0005
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0
lr_scheduler:
  desc: null
  value: steplr
warmup_multiplier:
  desc: null
  value: 1.0
warmup_epochs:
  desc: null
  value: 0
decay_step:
  desc: null
  value:
  - 2
  - 4
  - 8
decay_gamma:
  desc: null
  value: 0.5
poly_exp:
  desc: null
  value: 0.9
exp_name:
  desc: null
  value: blender_livingroom_skip1_res400_nerf_tcnn
model_type:
  desc: null
  value: nerf_tcnn
predict_normal:
  desc: null
  value: true
predict_mirror_mask:
  desc: null
  value: true
trace_secondary_rays:
  desc: null
  value: true
only_one_field:
  desc: null
  value: false
only_one_field_fine_epoch:
  desc: null
  value: 2
bound:
  desc: null
  value: 6.0
near:
  desc: null
  value: 0.05
far:
  desc: null
  value: 8.0
scale_factor:
  desc: null
  value: 1.0
val_idx:
  desc: null
  value: 0
train_skip_step:
  desc: null
  value: 1
max_recursive_level:
  desc: null
  value: 1
only_trace_rays_in_mirrors:
  desc: null
  value: true
for_vis:
  desc: null
  value: false
debug:
  desc: null
  value: false
train_geometry_stage:
  desc: null
  value: true
train_geometry_stage_end_epoch:
  desc: null
  value: 4
smooth_mirror_start_epoch:
  desc: null
  value: 2
train_mirror_mask_start_epoch:
  desc: null
  value: 2
train_normal_start_epoch:
  desc: null
  value: 1
detach_density_outside_mirror_for_mask_loss:
  desc: null
  value: false
detach_density_for_mask_loss:
  desc: null
  value: false
detach_density_for_normal_loss:
  desc: null
  value: false
detach_normal_in_reflection:
  desc: null
  value: false
woMaskRGBtoBlack:
  desc: null
  value: false
detach_ref_color_for_blend:
  desc: null
  value: false
normal_loss_only_inside_mirror:
  desc: null
  value: false
use_plane_consistent_loss:
  desc: null
  value: true
color_loss_weight:
  desc: null
  value: 1
normal_loss_weight:
  desc: null
  value: 0.0001
normal_reg_loss_weight:
  desc: null
  value: 0.1
mirror_mask_loss_weight:
  desc: null
  value: 0.1
plane_consistent_loss_weight:
  desc: null
  value: 0.1
